spring:
  datasource:
    hikari:
      maximum-pool-size: 10
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/localpetnet
      username: root
      password: root
# local mySql 환경 설정