spring:
  datasource:
    hikari:
      maximum-pool-size: 10
      driver-class-name: ENC(mgTL+u9PBOA2+XK/cUGANVm57eVqVyawlvrqiyxeb4cY6iocKudwnJrb3UKuWVct)
      jdbc-url: ENC(kYDfgeBRwMDpLHkVSy7FfHKLYtsxfiafb5q0o5b6dSflfsHb61xRO6YFt8c2rJMBpDVTdSMfbhk20izNu/YEJqNRmuwWnEkCUoBVc1zzCo1YB+d++Pzm0ibNeuCUCgcYSsDkvd03JrTcCoW1TYuWJyh0n73OrPRL)
      username: ENC(H0nB9oY4nvypGUvpeSNkP7ljEPKwFdrZ)
      password: ENC(KxR5WstGuk7GAKFKwYIBINYUa6VHsLKxtJvPexCsumc=)
server:
  log:
    path: logs